// B-100 P1.3 adversarial: derive Eq on structs containing enums and nested structs.
// Tests recursive structural equality generated by the compiler.

enum Color { Red, Green, Blue }

impl Eq for Color {
    fn eq(self, other: Color) -> Bool {
        match (self, other) {
            (Color::Red, Color::Red) => true,
            (Color::Green, Color::Green) => true,
            (Color::Blue, Color::Blue) => true,
            _ => false
        }
    }
}

struct Point { x: Int, y: Int }

impl Eq for Point {
    fn eq(self, other: Point) -> Bool {
        self.x == other.x && self.y == other.y
    }
}

struct Shape {
    origin: Point,
    color: Color,
    label: Str,
}

impl Eq for Shape {
    fn eq(self, other: Shape) -> Bool {
        self.origin == other.origin && self.color == other.color && self.label == other.label
    }
}

// Enum with struct payload
enum Figure {
    Circle(Int),
    Rect(Point, Point),
    Empty,
}

impl Eq for Figure {
    fn eq(self, other: Figure) -> Bool {
        match (self, other) {
            (Figure::Circle(r1), Figure::Circle(r2)) => r1 == r2,
            (Figure::Rect(a1, b1), Figure::Rect(a2, b2)) => a1 == a2 && b1 == b2,
            (Figure::Empty, Figure::Empty) => true,
            _ => false
        }
    }
}

// Generic eq through the chain
fn are_equal<T: Eq>(a: T, b: T) -> Bool { a == b }

fn main() {
    // Nested struct equality
    let s1 = Shape { origin: Point { x: 1, y: 2 }, color: Color::Red, label: "a" }
    let s2 = Shape { origin: Point { x: 1, y: 2 }, color: Color::Red, label: "a" }
    let s3 = Shape { origin: Point { x: 1, y: 2 }, color: Color::Blue, label: "a" }
    let s4 = Shape { origin: Point { x: 3, y: 2 }, color: Color::Red, label: "a" }
    print("shape_eq=${s1 == s2}")         // shape_eq=true
    print("shape_color=${s1 == s3}")      // shape_color=false
    print("shape_origin=${s1 == s4}")     // shape_origin=false

    // Generic dispatch with nested struct
    print("generic_shape=${are_equal(s1, s2)}")    // generic_shape=true
    print("generic_shape2=${are_equal(s1, s3)}")   // generic_shape2=false

    // Enum with struct payload
    let f1 = Figure::Rect(Point { x: 0, y: 0 }, Point { x: 10, y: 10 })
    let f2 = Figure::Rect(Point { x: 0, y: 0 }, Point { x: 10, y: 10 })
    let f3 = Figure::Rect(Point { x: 0, y: 0 }, Point { x: 5, y: 5 })
    let f4 = Figure::Circle(5)
    let f5 = Figure::Circle(5)
    let f6 = Figure::Empty
    let f7 = Figure::Empty
    print("rect_eq=${f1 == f2}")          // rect_eq=true
    print("rect_ne=${f1 == f3}")          // rect_ne=false
    print("circle_eq=${f4 == f5}")        // circle_eq=true
    print("cross_ne=${f1 == f4}")         // cross_ne=false
    print("empty_eq=${f6 == f7}")         // empty_eq=true

    // Generic dispatch with enum
    print("generic_fig=${are_equal(f1, f2)}")     // generic_fig=true
    print("generic_fig2=${are_equal(f4, f6)}")    // generic_fig2=false
}
